#ifndef CONFIG_H
#define CONFIG_H

#define KCM_GRUB2_VERSION "@KCM_GRUB2_VERSION@"
#define HAVE_IMAGEMAGICK @HAVE_IMAGEMAGICK@
#define HAVE_HD @HAVE_HD@
#define HAVE_QAPT @HAVE_QAPT@
#define HAVE_QPACKAGEKIT @HAVE_QPACKAGEKIT@

#endif
